// SPDX-License-Identifier: GPL-2.0-or-later
import { defineConfig, type Plugin } from 'vite';
import { fileURLToPath } from 'node:url';
import { createRequire } from 'node:module';
import { resolve } from 'node:path';

const appRoot = fileURLToPath(new URL('./', import.meta.url));
const { collectBrowserProvenance, collectBrowserSourceInventory } = createRequire(import.meta.url)('./scripts/browser-provenance.mjs') as {
  collectBrowserProvenance(root: string): unknown;
  collectBrowserSourceInventory(root: string): { path: string; bytes: number; sha256: string }[];
};

function reviewedSourceGuard(paths: Set<string>): Plugin {
  return {
    name: 'reviewed-browser-module-inputs',
    generateBundle() {
      for (const id of this.getModuleIds()) {
        // These wrappers are generated by the exact pinned build toolchain.
        if (id.startsWith('\0vite/') || id.startsWith('\0rolldown/') || /^\0@oxc-project\+runtime@[0-9.]+\/helpers\/esm\/[A-Za-z0-9]+\.js$/.test(id)) continue;
        const file = id.split('?')[0];
        if (!paths.has(resolve(file))) this.error('Browser build loaded an input outside its reviewed source inventory.');
      }
    },
  };
}

export default defineConfig(({ command }) => {
  const productionBuild = command === 'build';
  const buildInfo = productionBuild ? collectBrowserProvenance(appRoot) : null;
  const paths = productionBuild ? new Set(collectBrowserSourceInventory(appRoot).map(item => resolve(appRoot, item.path))) : new Set<string>();
  return {
    base: './',
    optimizeDeps: { entries: ['index.html'] },
    define: { __CONTENTLEDGER_BUILD__: JSON.stringify(buildInfo) },
    envDir: false,
    publicDir: false,
    css: { postcss: { plugins: [] } },
    resolve: { alias: { '@checker-platform': fileURLToPath(new URL('./src/platform-browser.ts', import.meta.url)) } },
    plugins: [
      ...(productionBuild ? [reviewedSourceGuard(paths)] : []),
      {
        name: 'local-browser-policy',
        apply: 'build',
        transformIndexHtml() {
          return [
            { tag: 'meta', attrs: { 'http-equiv': 'Content-Security-Policy', content: "default-src 'none'; script-src 'self'; style-src 'self'; img-src 'self' data:; font-src 'self'; worker-src 'self' blob:; connect-src 'none'; object-src 'none'; base-uri 'none'; form-action 'none'" }, injectTo: 'head-prepend' },
            { tag: 'meta', attrs: { name: 'referrer', content: 'no-referrer' }, injectTo: 'head-prepend' },
          ];
        },
      },
    ],
    ...(productionBuild ? { worker: { plugins: () => [reviewedSourceGuard(paths)] } } : {}),
    clearScreen: false,
    server: { host: '127.0.0.1', port: 1430, strictPort: true },
    preview: { host: '127.0.0.1', port: 1431, strictPort: true },
    envPrefix: [],
    build: { target: ['es2022', 'safari15'], sourcemap: false, modulePreload: { polyfill: false } },
  };
});
